version: '3'

services:
    db:
        image: arm64v8/mysql:oracle
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'Asdfgh123!'
            MYSQL_DATABASE: schedule_bot
